lda: Corpus.cpp main.cpp Evaluator.cpp LDAFrame.cpp OriginalSampler.h FastSampler.h FastSampler.cpp SparseSampler.h SparseSampler.cpp AliasDrawer.cpp
	g++ -o lda Corpus.cpp main.cpp Evaluator.cpp LDAFrame.cpp FastSampler.cpp SortedValueRankPair.cpp SparseSampler.cpp AliasDrawer.cpp
	./lda